### ISSUE TITLE
Parameter fitting in fast_oopsi.m fails for b

### ISSUE THREAD

**Issue by LaurenceA** [jovo/oopsi#2]
Nice code!  I was trying to do parameter estimation using fast_oopsi, and I found that the likelihood oscillates if I try to estimate the baseline flourescence.

A minimum working example:

```matlab
V = struct();
V.dt = 0.03
V.est_sig = 1;
V.est_lam = 1;
V.est_gam = 1;
V.est_a = 1;
V.fast_ignore_post = 1;
V.fast_iter_max = 100;
V.fast_plot = 1;

%The critical line
V.est_b = 1;

fast_oopsi(ones(1, 10000), V);
```

The problem appears to be in estimating b --- if we set `V.est_b=0`, then the oscillations disappear.

**Comment by jovo** [comment]
thanks!
for reference, there are better implementations now, some in python, and i
believe fred hamprecht will post a new one soon incorporating his spatial
filtering work as well...
