### ISSUE TITLE
 fluorescence time series

### ISSUE THREAD

**Issue by thangbui** [jovo/oopsi#3]
Hi Joshua,

Could you provide the real calcium trace data that you used for your papers please?

Thanks.

**Comment by jovo** [comment]
it is in the repo associated with each paper:

https://github.com/jovo/fast-oopsi/tree/master/data
https://github.com/jovo/smc-oopsi/tree/master/data

let me know if you have any problems!

On Friday, April 10, 2015, thangbui <notifications@github.com> wrote:

>  Hi Joshua,
>
> Could you provide the real calcium trace data that you used for your
> papers please?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jovo/oopsi/issues/3>.
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by thangbui** [comment]
Cool, thanks!
