### ISSUE TITLE
Receiving errors like "Undefined function or variable "C1" when using it for a single time series

### ISSUE THREAD

**Issue by caanalysislledo** [jovo/oopsi#4]
I have been trying to quantify spontaneous Ca recordings in the Olfactory bulb, when i came across your very attractive code on Github, fast-oopsi.
As I am new to the concept of spike deconvolution, i tried to include my traces in a Matlab matrix (a modification to your demo.m is attached), but i get an error:
"Undefined function or variable "C1.
Error in fast_oopsi/est_MAP (line 306)
                C    = C1;                      % update C
Error in fast_oopsi (line 166)
[n C posts(1)] = est_MAP(F,P);
Error in oopsie_test (line 35)
            [data(l).Nhat data(l).Phat] = fast_oopsi(F2,V,P);"
As suggested, I have tried passing each time-series as a vector on its own, but the same error persists.
Could you please help me figure out the problem. Thanks a lot in advance.
Highly obliged for your kind attention
Regards,
Soham

[a.zip](https://github.com/jovo/oopsi/files/356962/a.zip)

**Comment by jovo** [comment]
sorry for delay, i finally played with your data.
your traces have NaN's in them.

i have fixed the code to check for nan and output an error if that happens.  https://github.com/jovo/oopsi/commit/b65299f98777b5e917314f2b7bc8655caf1dd9f1


thanks!
